export const cinematicCopy = {
  pt: {
    operation: 'Operação Maré Negra',
    subtitle: 'Localize os transmissores. Reconstrua a rota de extração.',
    classification: 'ARQUIVO FICTÍCIO / NÍVEL 07',
    network: 'Rede de interceptação',
    radar: 'Radar ativo',
    paused: 'Radar pausado',
    signalView: 'Sinais',
    cityView: 'Planta',
    layer: 'Camada do mapa',
    tracking: 'ALVO RASTREADO',
    bearing: 'VETOR DE ESCUTA',
    scanPhases: [
      'Varrendo canais da baía',
      'Triangulando o transmissor',
      'Fixando frequência',
    ],
    capturePhases: [
      'Isolando a portadora',
      'Decodificando os fragmentos',
      'Reconstruindo a mensagem',
    ],
    sequence: 'Sequência simulada',
    skip: 'Concluir agora',
    cancel: 'Abortar',
    spectrum: 'Espectro de frequência',
    waveform: 'Forma de onda calculada a partir da sintonia',
    transmission: 'Transmissão cifrada',
    waiting: 'AGUARDANDO INTERCEPTAÇÃO',
    decoded: 'MENSAGEM DECODIFICADA',
    extraction: 'ROTA DE EXTRAÇÃO RECONSTRUÍDA',
    command: 'Linha de comando',
    send: 'Executar',
    commandHint:
      'scan · tune 88 · assist · intercept · target b02 · cancel · reset',
    invalid: 'Comando não reconhecido. Digite help para ver os comandos.',
    busy: 'Sequência em andamento. Use cancel para abortar.',
    needScan: 'Primeiro execute scan neste setor.',
    needSignal: 'Sintonize o sinal em pelo menos 84%.',
    already: 'Este setor já foi processado.',
    started: 'Sequência iniciada.',
    accepted: 'Comando executado.',
    cancelled: 'Sequência cancelada.',
    motion: 'Movimento',
    sound: 'Som',
    unavailable: 'Áudio indisponível',
    on: 'Ligado',
    off: 'Desligado',
    focus: 'Modo imersivo',
    exitFocus: 'Sair do modo imersivo',
    recovered: 'RECUPERADOS',
    channel: 'CANAL',
    target: 'ALVO',
    listening: 'ESCUTA',
    motionPreference: 'Movimento reduzido ativado no sistema.',
  },
  en: {
    operation: 'Operation Black Tide',
    subtitle: 'Locate the transmitters. Reconstruct the extraction route.',
    classification: 'FICTIONAL FILE / LEVEL 07',
    network: 'Interception network',
    radar: 'Radar active',
    paused: 'Radar paused',
    signalView: 'Signals',
    cityView: 'Blueprint',
    layer: 'Map layer',
    tracking: 'TARGET TRACKED',
    bearing: 'LISTENING VECTOR',
    scanPhases: [
      'Sweeping bay channels',
      'Triangulating transmitter',
      'Locking frequency',
    ],
    capturePhases: [
      'Isolating carrier',
      'Decoding fragments',
      'Reconstructing message',
    ],
    sequence: 'Simulated sequence',
    skip: 'Complete now',
    cancel: 'Abort',
    spectrum: 'Frequency spectrum',
    waveform: 'Waveform calculated from tuning',
    transmission: 'Encrypted transmission',
    waiting: 'AWAITING INTERCEPTION',
    decoded: 'MESSAGE DECODED',
    extraction: 'EXTRACTION ROUTE RECONSTRUCTED',
    command: 'Command line',
    send: 'Execute',
    commandHint:
      'scan · tune 88 · assist · intercept · target b02 · cancel · reset',
    invalid: 'Unknown command. Type help to see available commands.',
    busy: 'Sequence running. Use cancel to abort.',
    needScan: 'Run scan on this sector first.',
    needSignal: 'Tune the signal to at least 84%.',
    already: 'This sector has already been processed.',
    started: 'Sequence started.',
    accepted: 'Command executed.',
    cancelled: 'Sequence cancelled.',
    motion: 'Motion',
    sound: 'Sound',
    unavailable: 'Audio unavailable',
    on: 'On',
    off: 'Off',
    focus: 'Immersive mode',
    exitFocus: 'Exit immersive mode',
    recovered: 'RECOVERED',
    channel: 'CHANNEL',
    target: 'TARGET',
    listening: 'LISTENING',
    motionPreference: 'Reduced motion is enabled in system settings.',
  },
}
