export const consoleCopy = {
  pt: {
    back: 'Laboratório',
    language: 'Switch to English',
    simulation: 'Simulação local',
    eyebrow: 'Divisão de escuta / terminal 07',
    title: 'Toda cidade tem seus segredos.',
    intro:
      'Três sinais cruzam a baía. Encontre a frequência. Escute o que ficou nas entrelinhas.',
    map: 'Cartografia da baía',
    mapHint: 'Selecione um setor no mapa ou na lista.',
    mapLabel: 'Mapa esquemático de Neon Bay, com três setores selecionáveis.',
    north: 'N',
    water: 'CANAL DE NEON',
    district: 'DISTRITO INDUSTRIAL',
    sector: 'Setor',
    receiver: 'Receptor analógico',
    frequency: 'Frequência',
    signal: 'Qualidade do sinal',
    unknown: 'Aguardando varredura',
    locked: 'Sinal alinhado',
    tuneHint:
      'Use o controle ou as setas do teclado. A partir de 84%, a mensagem fica legível.',
    scan: 'Varrer setor',
    scanned: 'Setor mapeado',
    assist: 'Sintonizar para mim',
    capture: 'Interceptar mensagem',
    captured: 'Mensagem interceptada',
    next: 'Próximo setor',
    reset: 'Reiniciar operação',
    resetHint: 'Apaga o progresso desta simulação.',
    briefing: 'Seu próximo movimento',
    stepScan: '01 / Localizar',
    stepTune: '02 / Sintonizar',
    stepRead: '03 / Interceptar',
    stepDone: 'Arquivo recuperado',
    scanHint: 'Faça uma varredura para descobrir o canal deste setor.',
    readHint:
      'O sinal está legível. Intercepte a mensagem para revelar o arquivo.',
    doneHint:
      'Mensagem salva nesta sessão. Explore outro setor para continuar.',
    complete: 'Operação concluída',
    completeHint:
      'Os três fragmentos revelam uma rota. A saída é pelo Dock 07.',
    dossier: 'Arquivo de campo',
    empty: 'Nenhuma transmissão interceptada neste setor.',
    log: 'Registro da operação',
    progress: 'Arquivos recuperados',
    help: 'Como operar este terminal',
    helpText:
      'Escolha um setor, faça a varredura, ajuste a frequência e intercepte. O botão “Sintonizar para mim” ajuda a alinhar o sinal. Você também pode usar Tab, Enter e as setas no controle de frequência. Reiniciar limpa os três arquivos.',
    footer:
      'Ficção interativa / sem conexão com sistemas reais / progresso apenas nesta visita',
    explore: 'Explorar outros estudos',
    source: 'Ver código',
    motion: 'Efeito de varredura',
    motionOn: 'Ligado',
    motionOff: 'Desligado',
    events: {
      boot: 'Terminal iniciado',
      select: 'Setor selecionado',
      scan: 'Frequência localizada',
      capture: 'Arquivo recuperado',
      assist: 'Sintonia assistida',
    },
    sectors: {
      dock: {
        name: 'Dock 07',
        type: 'Acesso portuário',
        text: 'Entre guindastes de cobre e névoa salgada, um transmissor espera a próxima embarcação.',
        message:
          'O cargueiro não transporta carvão. Procure a caixa com o selo de uma engrenagem partida.',
        clue: 'Pista 01 / O selo',
      },
      boiler: {
        name: 'Casa das caldeiras',
        type: 'Núcleo de vapor',
        text: 'A tubulação conduz mais que vapor. Uma mensagem viaja pelo velho circuito de manutenção.',
        message:
          'A válvula de cobre abre a passagem de serviço. O mapa está gravado no verso do selo.',
        clue: 'Pista 02 / A passagem',
      },
      tower: {
        name: 'Torre de escuta',
        type: 'Retransmissão',
        text: 'Acima dos telhados, a antena mecânica guarda o último fragmento da operação.',
        message:
          'Quando o farol acender, siga a passagem até o Dock 07. A baía guarda segredos, mas também saídas.',
        clue: 'Pista 03 / A saída',
      },
    },
  },
  en: {
    back: 'Laboratory',
    language: 'Mudar para português',
    simulation: 'Local simulation',
    eyebrow: 'Listening division / terminal 07',
    title: 'Every city keeps its secrets.',
    intro:
      'Three signals cross the bay. Find the frequency. Hear what was left between the lines.',
    map: 'Bay cartography',
    mapHint: 'Select a sector on the map or in the list.',
    mapLabel: 'Schematic map of Neon Bay with three selectable sectors.',
    north: 'N',
    water: 'NEON CHANNEL',
    district: 'INDUSTRIAL DISTRICT',
    sector: 'Sector',
    receiver: 'Analog receiver',
    frequency: 'Frequency',
    signal: 'Signal quality',
    unknown: 'Awaiting scan',
    locked: 'Signal aligned',
    tuneHint:
      'Use the slider or keyboard arrows. At 84% or higher, the message becomes readable.',
    scan: 'Scan sector',
    scanned: 'Sector mapped',
    assist: 'Tune for me',
    capture: 'Intercept message',
    captured: 'Message intercepted',
    next: 'Next sector',
    reset: 'Restart operation',
    resetHint: 'Clears progress in this simulation.',
    briefing: 'Your next move',
    stepScan: '01 / Locate',
    stepTune: '02 / Tune',
    stepRead: '03 / Intercept',
    stepDone: 'File recovered',
    scanHint: 'Scan to discover this sector’s channel.',
    readHint:
      'The signal is readable. Intercept the message to reveal the file.',
    doneHint:
      'Message saved for this session. Explore another sector to continue.',
    complete: 'Operation complete',
    completeHint:
      'The three fragments reveal a route. The exit is through Dock 07.',
    dossier: 'Field file',
    empty: 'No transmission intercepted in this sector.',
    log: 'Operation log',
    progress: 'Recovered files',
    help: 'How to operate this terminal',
    helpText:
      'Choose a sector, scan, tune the frequency and intercept. “Tune for me” helps align the signal. You can also use Tab, Enter and the frequency slider’s arrow keys. Restart clears all three files.',
    footer:
      'Interactive fiction / no connection to real systems / progress for this visit only',
    explore: 'Explore other studies',
    source: 'View code',
    motion: 'Scan effect',
    motionOn: 'On',
    motionOff: 'Off',
    events: {
      boot: 'Terminal initialized',
      select: 'Sector selected',
      scan: 'Frequency located',
      capture: 'File recovered',
      assist: 'Assisted tuning',
    },
    sectors: {
      dock: {
        name: 'Dock 07',
        type: 'Harbor access',
        text: 'Between copper cranes and salt mist, a transmitter awaits the next ship.',
        message:
          'The freighter is not carrying coal. Look for the crate marked with a broken gear seal.',
        clue: 'Clue 01 / The seal',
      },
      boiler: {
        name: 'Boiler house',
        type: 'Steam core',
        text: 'These pipes carry more than steam. A message travels through the old maintenance circuit.',
        message:
          'The copper valve opens the service passage. The map is engraved on the back of the seal.',
        clue: 'Clue 02 / The passage',
      },
      tower: {
        name: 'Listening tower',
        type: 'Relay station',
        text: 'Above the rooftops, a mechanical antenna holds the operation’s final fragment.',
        message:
          'When the beacon lights up, follow the passage to Dock 07. The bay keeps secrets, but also ways out.',
        clue: 'Clue 03 / The exit',
      },
    },
  },
}
