export const missionCopy = {
  pt: {
    back: 'Laboratório',
    language: 'Switch to English',
    restart: 'Reiniciar missão',
    phases: ['Servidor', 'Interceptação', 'Controle de acesso'],
    simulation: 'Ficção interativa · sessão local',
    session: 'SESSÃO',
    company: 'Infraestrutura portuária & sistemas de energia',
    eyebrow: '01 / ARQUIVO CORPORATIVO',
    title: 'Os segredos têm um endereço.',
    intro:
      'Você está no arquivo da Asterion. Encontre o dossiê da Operação Maré Negra para estabelecer uma conexão com a baía.',
    objective: 'OBJETIVO ATUAL',
    objectiveText: 'Localize e abra BLACK_TIDE.nb',
    folders: 'Volumes montados',
    files: 'Diretório de arquivos',
    preview: 'Inspeção de arquivo',
    volume: 'Arquivo operacional',
    archive: 'Arquivo histórico',
    system: 'Estado do servidor',
    fileNames: [
      'Manifesto de carga',
      'Diretório de pessoal',
      'Nota de manutenção',
      'Operação Maré Negra',
    ],
    fileKinds: [
      'LOG DE TRANSPORTE',
      'REGISTRO INTERNO',
      'ORDEM DE SERVIÇO',
      'DOSSIÊ RESTRITO',
    ],
    fileText: [
      'Terminal 07. A carga declarada é carvão, mas os registros de pesagem não conferem. Uma caixa com o selo de uma engrenagem partida foi retirada do inventário.',
      'Turno noturno: equipe de manutenção na casa das caldeiras. Torre de escuta operando sem supervisão. Acesso ao cais suspenso até segunda ordem.',
      'Protocolo de manutenção: isole o circuito de vigilância antes de energizar os portões. Patch de energia: A → C, B → A, C → B. Os canais de rádio fornecem as chaves de acesso.',
      'Três transmissões. Uma passagem de serviço. Nenhum registro oficial. Abra o receptor de campo, recupere os três sinais e use as frequências para liberar a rota de extração.',
    ],
    connect: 'Abrir receptor de campo',
    inspectHint: 'Selecione um arquivo para inspecionar seu conteúdo.',
    restricted: 'CONEXÃO DE CAMPO DISPONÍVEL',
    readOnly: 'SOMENTE LEITURA',
    rack: 'Gabinete de rede / R-07',
    rackLabel:
      'Ilustração do gabinete com módulos de energia, arquivo e comunicação',
    telemetry: 'Telemetria simulada',
    latency: 'Latência',
    storage: 'Arquivo',
    temp: 'Temperatura',
    log: 'Registro da sessão',
    serverLogs: [
      'Volume operacional montado',
      'Índice de arquivos disponível',
      'Dossiê BLACK_TIDE.nb localizado',
    ],
    help: 'Instruções da missão',
    helpText:
      'Abra BLACK_TIDE.nb. Na próxima etapa, selecione cada setor, faça a varredura, sintonize e intercepte. As três frequências recuperadas liberam o controle dos portões.',
    signalTitle: 'Três sinais. Uma chave de entrada.',
    signalText:
      'Recupere as três transmissões. Depois, abra o controle de acesso para liberar a passagem de serviço.',
    continue: 'Acessar controle dos portões',
    signalsDone: 'Chaves de acesso recuperadas',
    controlEyebrow: '03 / INFRAESTRUTURA REMOTA',
    controlTitle: 'Abra uma saída na cidade.',
    controlIntro:
      'Os sinais revelaram a rota. Isole a vigilância, reconecte a energia e libere os três portões em sequência.',
    surveillance: 'Circuito de vigilância',
    live: 'ATIVO',
    isolated: 'ISOLADO',
    isolate: 'Isolar circuito',
    isolatedText: 'Circuito isolado. Manutenção liberada.',
    camera: 'CÂMERA 07 / PASSAGEM DE SERVIÇO',
    cameraLabel:
      'Vista esquemática da passagem com três portões que abrem conforme a missão avança',
    patch: 'Matriz de energia',
    patchHint:
      'Reconecte os três relés. Cada clique muda o destino. Diagrama de manutenção: A → C · B → A · C → B.',
    relay: 'Relé',
    destination: 'Destino',
    linked: 'ENERGIA ESTÁVEL',
    unlinked: 'RECONFIGURAÇÃO NECESSÁRIA',
    access: 'Autorização de passagem',
    gateNames: [
      'Portão de serviço',
      'Eclusa das caldeiras',
      'Portão do Dock 07',
    ],
    locked: 'FECHADO',
    open: 'ABERTO',
    keyring: 'Chaves recuperadas',
    keyHint:
      'Use a frequência indicada, com três dígitos. Exemplo: 88 MHz → 088.',
    code: 'Chave do portão',
    unlock: 'Autorizar abertura',
    gateHelp:
      'Libere os portões na ordem da rota. A matriz fica travada após a primeira abertura.',
    feedback: {
      ready: 'Aguardando autorização do operador.',
      isolate: 'Isole o circuito de vigilância antes de abrir a passagem.',
      route:
        'A matriz está desalinhada. Confira o diagrama A → C, B → A, C → B.',
      code: 'Chave incorreta. Consulte a frequência do portão nas chaves recuperadas.',
      opened: 'Autorização aceita. Portão aberto.',
    },
    extraction: 'Confirmar extração',
    extractionReady: 'Passagem livre. O Dock 07 espera por você.',
    completeEyebrow: 'OPERAÇÃO MARÉ NEGRA / CONCLUÍDA',
    completeTitle: 'Você encontrou a saída.',
    completeText:
      'O arquivo revelou a baía. Os sinais revelaram a rota. Agora, os portões estão abertos e a carga saiu do alcance da Asterion.',
    report: 'Relatório de operação',
    reportItems: [
      'Dossiê localizado',
      'Transmissões recuperadas',
      'Portões liberados',
    ],
    replay: 'Iniciar uma nova operação',
    replayHint:
      'Reinicia arquivos, sinais, relés e portões. Você pode repetir quantas vezes quiser.',
    footer: 'ASTERION SYSTEMS / NEON BAY — uma história que você opera.',
  },
  en: {
    back: 'Lab',
    language: 'Mudar para português',
    restart: 'Restart mission',
    phases: ['Server', 'Interception', 'Access control'],
    simulation: 'Interactive fiction · local session',
    session: 'SESSION',
    company: 'Harbor infrastructure & energy systems',
    eyebrow: '01 / CORPORATE ARCHIVE',
    title: 'Every secret has an address.',
    intro:
      'You are inside the Asterion archive. Find the Operation Black Tide dossier to establish a connection to the bay.',
    objective: 'CURRENT OBJECTIVE',
    objectiveText: 'Find and open BLACK_TIDE.nb',
    folders: 'Mounted volumes',
    files: 'File directory',
    preview: 'File inspection',
    volume: 'Operations archive',
    archive: 'Historical archive',
    system: 'Server status',
    fileNames: [
      'Cargo manifest',
      'Personnel directory',
      'Maintenance note',
      'Operation Black Tide',
    ],
    fileKinds: [
      'TRANSPORT LOG',
      'INTERNAL RECORD',
      'SERVICE ORDER',
      'RESTRICTED DOSSIER',
    ],
    fileText: [
      'Terminal 07. The declared cargo is coal, but the weight records do not match. A crate bearing a broken gear seal has been removed from the inventory.',
      'Night shift: maintenance crew in the boiler house. Listening tower operating unattended. Dock access suspended until further notice.',
      'Maintenance protocol: isolate surveillance before powering the gates. Power patch: A → C, B → A, C → B. Radio channels provide the access keys.',
      'Three transmissions. One service passage. No official record. Open the field receiver, recover all three signals and use their frequencies to clear the extraction route.',
    ],
    connect: 'Open field receiver',
    inspectHint: 'Select a file to inspect its contents.',
    restricted: 'FIELD CONNECTION AVAILABLE',
    readOnly: 'READ ONLY',
    rack: 'Network cabinet / R-07',
    rackLabel:
      'Cabinet illustration showing power, archive and communication modules',
    telemetry: 'Simulated telemetry',
    latency: 'Latency',
    storage: 'Archive',
    temp: 'Temperature',
    log: 'Session log',
    serverLogs: [
      'Operations volume mounted',
      'File index available',
      'BLACK_TIDE.nb dossier located',
    ],
    help: 'Mission instructions',
    helpText:
      'Open BLACK_TIDE.nb. Next, select each sector, scan, tune and intercept. The three recovered frequencies unlock gate control.',
    signalTitle: 'Three signals. One way in.',
    signalText:
      'Recover all three transmissions. Then open access control to clear the service passage.',
    continue: 'Open gate control',
    signalsDone: 'Access keys recovered',
    controlEyebrow: '03 / REMOTE INFRASTRUCTURE',
    controlTitle: 'Find a way out of the city.',
    controlIntro:
      'The signals revealed the route. Isolate surveillance, reconnect power and release the three gates in sequence.',
    surveillance: 'Surveillance circuit',
    live: 'LIVE',
    isolated: 'ISOLATED',
    isolate: 'Isolate circuit',
    isolatedText: 'Circuit isolated. Maintenance enabled.',
    camera: 'CAMERA 07 / SERVICE PASSAGE',
    cameraLabel:
      'Schematic passage view with three gates that open as the mission progresses',
    patch: 'Power matrix',
    patchHint:
      'Reconnect all three relays. Each click changes the destination. Maintenance diagram: A → C · B → A · C → B.',
    relay: 'Relay',
    destination: 'Destination',
    linked: 'POWER STABLE',
    unlinked: 'RECONFIGURATION REQUIRED',
    access: 'Passage authorization',
    gateNames: ['Service gate', 'Boiler airlock', 'Dock 07 gate'],
    locked: 'CLOSED',
    open: 'OPEN',
    keyring: 'Recovered keys',
    keyHint:
      'Use the indicated frequency with three digits. Example: 88 MHz → 088.',
    code: 'Gate key',
    unlock: 'Authorize opening',
    gateHelp:
      'Release gates in route order. The matrix locks after the first opening.',
    feedback: {
      ready: 'Awaiting operator authorization.',
      isolate: 'Isolate surveillance before opening the passage.',
      route: 'Matrix misaligned. Check the A → C, B → A, C → B diagram.',
      code: 'Incorrect key. Check this gate’s frequency in the recovered keys.',
      opened: 'Authorization accepted. Gate open.',
    },
    extraction: 'Confirm extraction',
    extractionReady: 'Passage clear. Dock 07 is waiting for you.',
    completeEyebrow: 'OPERATION BLACK TIDE / COMPLETE',
    completeTitle: 'You found the way out.',
    completeText:
      'The archive revealed the bay. The signals revealed the route. Now the gates are open and the cargo is beyond Asterion’s reach.',
    report: 'Operation report',
    reportItems: [
      'Dossier located',
      'Transmissions recovered',
      'Gates released',
    ],
    replay: 'Start a new operation',
    replayHint:
      'Resets files, signals, relays and gates. Replay as many times as you like.',
    footer: 'ASTERION SYSTEMS / NEON BAY — a story you operate.',
  },
}
